[package]
name = "sqlite3diff"
version = "0.0.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
clap = { version = "4.4.12", features = ["derive"] }
indexmap = "2.1.0"
libc = "0.2.151"
nohash = "0.2.0"
rand = "0.8.5"
